name: Deploy to Target Server via Bastion with Deploy Keys

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH for Bastion and Target Servers
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.INTERMEDIATE_SSH_KEY }}" > ~/.ssh/bastion_id_rsa
        ssh -i ~/.ssh/bastion_id_rsa -N ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}
        echo "${{ secrets.TARGET_DEPLOY_KEY }}" > ~/.ssh/target_id_rsa
        ssh -i ~/.ssh/target_id_rsa ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }}
        
    - name: Deploy via Bastion Host
      run: |
            cd ~/CycloEval
            docker build -t localhost:32000/frontend:latest -f client/Dockerfile ./client
            docker push localhost:32000/frontend:latest
            docker build -t localhost:32000/backend:latest -f server/Dockerfile ./server
            docker push localhost:32000/backend:latest

            microk8s kubectl apply -f k8s/client-deployment.yaml
            microk8s kubectl apply -f k8s/server-deployment.yaml
