# Azure Web App Deployment Workflow
name: Build and Deploy Full-Stack App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build React Frontend
        run: |
          cd client
          npm install
          npm run build
          cd ..
          mkdir -p deployment/frontend
          cp -r client/dist/* deployment/frontend/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Package Backend
        run: |
          mkdir -p deployment/server
          cp -r server/* deployment/server/

      - name: Create Deployment Package
        run: |
          cd deployment
          zip -r ../release.zip .
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Unzip Artifact
        run: unzip release.zip -d deployment

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cycloeval'
          package: ./deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9E3CD55F706E40649CB649AD613C0B94 }}
